x = int(input("enter x value "))
y = float(input("enter y value "))
z = bool(input("enter z value "))
print("Value of x = ", x)
print("Value of y = ", y)
print("Value of z = ", z)
print(type(x))
print(type(y))
print(type(z))